from features.cochleagram import Cochleagram
from features.spectrogram import Spectrogram
from features.mel_spectrogram import MelSpectrogram
from features.mfcc import MFCC
from features.PCA import PCA
from features.lfcc import LFCC
from features.mfcc_lib import MFCC_LIB
from features.STFT import STFT
from features.scalogram import Scalogram
from features.zero_crossing import Zero_crossing
from features.augmentMelSTFT import AugmentMelSTFT